### ISSUE TITLE
how to connect pwa studio graphql to nodejento 

### ISSUE THREAD

**Issue by sivamind** [Genaker/nodejento#1]
I would like to use pwa studio with nodejento?
can you give some idea?

**Comment by Genaker** [comment]
It is easy. You need to implement graphQL or create a component which will
use Nodejento API instead of the Magento API.

It is really easy implement graphQL with Nodejento.

Resolve helpers

import { resolver } from "graphql-sequelize";
resolver(SequelizeModel[, options]);

A helper for resolving graphql queries targeted at Sequelize models or
associations. Please take a look at the tests
<https://github.com/mickhansen/graphql-sequelize/blob/master/test/integration/resolver.test.js>
to
best get an idea of implementation.

Features

   - Automatically converts args to where if arg keys matches model
   attributes
   - Automatically converts an arg named 'limit' to a sequelize limit
   - Automatically converts an arg named 'order' to a sequelize order

However, it is better to use REST api vs Graph QL without additional
obfuscation layer.
